### ISSUE TITLE
onDismissRequest is called twice when bottom sheet is dismissed by swiping down

### ISSUE THREAD

**Issue by olshevski** [holixfactory/bottomsheetdialog-compose#1]
Hi, I really like you library and I'm trying to integrate it with my own Compose Navigation lib. I've noticed that swiping down causes the current BottomSheetDialog to call `onDismissRequest` twice, which breaks some logic for me. In all other cases this callback is always called once.

Could you maybe fix this issue and make it be called only once on swipe down? The current behaviour is very much unexpected and error-prone.

**Comment by workspace** [comment]
@olshevski There was some reason to add it. I'll check it again and resolve issue with #2

**Comment by workspace** [comment]
@olshevski BottomSheeetDialog (View) has own logic to cancel. I tried to handle animation and cancel logic both, however, it called onDismissRequest twice unintentionally. 

I resolved this issue with new feature `dismissWithAnimation` property 🎉 which is handling animation and cancel logic both properly.

**Comment by workspace** [comment]
@olshevski  Version `1.0.2` is published(or ongoing). I hope this new version can resolve your issue.

**Comment by olshevski** [comment]
Working great, thank you!
