### ISSUE TITLE
Compose Version 1.4

### ISSUE THREAD

**Issue by jeongwoobin** [holixfactory/bottomsheetdialog-compose#16]
혹시 compose 1.4에서도 기능 작동이 잘 되나요??
테스트해봤을때 crash가 발생하는 것 같습니다.

**Comment by workspace** [comment]
안녕하세요. 혹시 어떤 exception이 나는지 첨부해주실 수 있나요?

**Comment by workspace** [comment]
혹시 아래 exception이 맞을까요?

> java.lang.NoSuchMethodError: No static method rememberNestedScrollInteropConnection(Landroidx/compose/runtime/Composer;I)Landroidx/compose/ui/input/nestedscroll/NestedScrollConnection;

**Comment by workspace** [comment]
저희도 한 이슈 때문에 프로덕션에 compose 1.4를 적용했는데 같은 문제가 발생하고 있었네요. 다행히 잘 쓰이지 않는 곳에 적용해뒀던터라 큰 문제가 되기 전 발견하게 된 것 같습니다. 오늘 중 수정해볼게요! 제보 감사합니다.

**Comment by jeongwoobin** [comment]
확인 감사합니다.

**Comment by workspace** [comment]
1.2.0으로 배포될 예정입니다.

**Comment by workspace** [comment]
1.2.0이 배포되었습니다. 저희 프로젝트(compose 1.4.0-beta01)에서도 크래시 나던 것이 잘 작동하네요. 우빈님의 프로젝트도 문제가 잘 해결되시길 기원합니다.
