### ISSUE TITLE
v1.2.0 이후 키보드 관련 이슈.

### ISSUE THREAD

**Issue by dylan-kwon** [holixfactory/bottomsheetdialog-compose#17]
v1.2.0 이후로 키보드 동작이 이상해진 거 같습니다.

`BottomSheetDialog` 내부에 `TextField`가 있으면 키보드가 나타나지 않고, 
팝업이 닫히면 그때서야 키보드가 올라옵니다.

아래 영상은 샘플 코드에서 `TextField`만 추가해서 테스트했습니다.

[untitled.webm](https://user-images.githubusercontent.com/21299684/223055711-c6605fb4-7c05-40ab-9c11-4be80e623381.webm)

**Comment by dylan-kwon** [comment]
아마 compose 1.4.0 문제로 보입니다.

**Comment by workspace** [comment]
안녕하세요. 제보 감사합니다. 확인 후 커멘트 드리겠습니다!

**Comment by workspace** [comment]
문제를 확인했습니다. 말씀하신 것과 같이 샘플 앱에 TextField만을 추가하는 것으로 재현이 되네요. BottomSheetDialog의 내부 구현은 95%이상 Dialog Composable과 동일하여 Dialog Composable에서도 같은 문제가 있는지 확인했으나 멀쩡하네요😢 좀 더 조사해봐야 할 것 같습니다.

**Comment by workspace** [comment]
@dylan-kwon 안녕하세요. 지난 주에 들여다보고 더 이슈 해결에 진전이 없는 상태입니다. 일단은 이슈 해결 데드라인을 compose 1.4.0 정식 출시 시점으로 잡아두겠습니다. 혹시나 이 문제를 해결해 라이브러리에 기여해주신다면 정말 기쁠 것 같습니다.

**Comment by workspace** [comment]
BottomSheet + TextField 이슈에 대해 파본 미디엄 글이 있어 소개 드립니다. 알고보니 22년 12월 누군가 1.4.0-alpha03으로 테스트해보고 제보를 했던 이슈라고 하네요. stable 출시까지 3달이나 있었는데 아쉬운 부분입니다. 본문의 내용을 참고하여 곧 임시로 문제가 해결된 버전을 배포해보겠습니다. 👍 

 https://link.medium.com/qRO3dQcXQyb

**Comment by workspace** [comment]
하하 놀랍게도... 제가 좀만 더 신경 썼으면 아예 없었을 수도 있는 문제네요. 
Dialog composable이 있는 AndroidDialog.android.kt 파일에서 필요한 만큼 가져왔는데

androidx.compose.ui.window.DialogWindowProvider도 재정의를 해버려서 적절한 window를 찾지 못했던 것이었습니다.

```kotlin
// InputMethodManager.kt
private fun View.findWindow(): Window? =
    (parent as? DialogWindowProvider)?.window
        ?: context.findWindow()
```

**Comment by workspace** [comment]
compose 1.4용 해결된 버전이 1.2.1로 배포 되었습니다 🎉🙏👍🚀

**Comment by dylan-kwon** [comment]
감사합니다!
